    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install cloud-init
      run: sudo apt-get update && sudo apt-get install -y cloud-init

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pylint
      run: |
        pylint backend/ --exit-zero
      continue-on-error: true

    - name: Run pytest
      run: |
        pytest backend/ --maxfail=1 --disable-warnings
=======
      # Check out the repository
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Install and run pylint
      - name: Run pylint
        run: |
          pip install pylint
          pylint $(git ls-files '*.py')

      # Install and run pytest
      - name: Run pytest
        run: |
          pip install pytest
          pytest