name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: [ self-hosted ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install cloud-init
      run: sudo apt-get update && sudo apt-get install -y cloud-init

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pylint
      run: |
        pylint backend/ --exit-zero
      continue-on-error: true

    - name: Run pytest
      run: |
        pytest backend/ --maxfail=1 --disable-warnings
